CREATE TABLE CLASSES_<YOUR_NAME>
(
  DEPARTMENT        CHAR(3 BYTE),
  COURSE            NUMBER(3),
  DESCRIPTION       VARCHAR2(2000 BYTE),
  MAX_STUDENTS      NUMBER(3),
  CURRENT_STUDENTS  NUMBER(3),
  NUM_CREDITS       NUMBER(1),
  ROOM_ID           NUMBER(5)
);

