CREATE TABLE EMPLOYEES_<YOUR_NAME>
(
  EMPLOYEE_ID     NUMBER(6),
  FIRST_NAME      VARCHAR2(20 BYTE),
  LAST_NAME       VARCHAR2(25 BYTE),
  EMAIL           VARCHAR2(25 BYTE),
  PHONE_NUMBER    VARCHAR2(20 BYTE),
  HIRE_DATE       DATE,
  JOB_ID          VARCHAR2(10 BYTE),
  SALARY          NUMBER(8,2),
  COMMISSION_PCT  NUMBER(2,2),
  MANAGER_ID      NUMBER(6),
  DEPARTMENT_ID   NUMBER(4)
);
